name: Privileges
main: net.krinsoft.privileges.Privileges
author: krinsdeath
version: maven-version-number
load: startup

commands:
  ################
  # BASE COMMAND #
  ################
  privileges:
    description: The commands for manipulating player permissions
    aliases: [priv]
    usage: /<command> [section] [options]...
  ############################
  # BACKUP & FILE MANAGEMENT #
  ############################
  pbackup:
    description: Creates a snapshot of the current config files with the specified name.
    usage: /<command> [backup]
  prestore:
    description: Restores a snapshot with the specified name.
    usage: /<command> [backup]
  psave:
    description: Saves all of the Privileges config files.
    usage: /<command>
  pload:
    description: Loads all of Privileges config files without first saving them.
    usage: /<command>
  preload:
    description: Saves and reloads all of the Privileges config files.
    usage: /<command>
  ##########################
  # GENERAL ADMINISTRATION #
  ##########################
  pdebug:
    description: Toggles debug mode for additional information in the logger.
    usage: /<command> [boolean]
  pcheck: 
    description: Checks the status of a permission node for yourself or the specified user.
    aliases: [pc]
    usage: /<command> [player] [node]
  plist:
    description: Lists all nodes for the specified user.
    aliases: [pl]
    usage: /<command> [player] [page]
  pinfo:
    description: Shows miscellaneous info about the given user
    aliases: [pi]
    usage: /<command> [player]
  ##################
  # GROUP COMMANDS #
  ##################
  pgroup:
    description: Shows a basic list of available group-based commands.
    aliases: [pg]
    usage: /<command>
  pgroupl:
    description: Lists all available groups.
    aliases: [pgl]
    usage: /<command>
  pggroups:
    description: Sets the specified player's group
    aliases: [pgs]
    usage: /<command> [player] [group]
  pgroupr:
    description: Removes the specified group
    aliases: [pgr]
    usage: /<command> [group] --safe
  pgroupc:
    description: Creates the specified group with the given rank
    aliases: [pgc]
    usage: /<command> [group] [rank]
  pgroupps:
    description: Sets the specified permission for the given group
    aliases: [pgps]
    usage: /<command> [group] [node] [true|false]
  pgrouppr:
    description: Removes the specified permission from the given group
    aliases: [pgpr]
    usage: /<command> [group] [node]
  #################
  # USER COMMANDS #
  #################
  puser:
    description: Shows a basic list of all available user-based commands.
    aliases: [pu]
    usage: /<command>
  puserpr:
    description: Removes the specified permission from the given user
    aliases: [pupr]
    usage: /<command> [player] [node]
  puserps:
    description: Sets the specified permission for the given user
    aliases: [pups]
    usage: /<command> [player] [node] [true|false]
  ##########################
  # MISCELLANEOUS COMMANDS #
  ##########################
  promote:
    description: Promotes the specified player to the next higher rank
    aliases: [pro]
    usage: /<command> [player]
  demote:
    description: Demotes the specified player to the next lowest rank
    aliases: [dem]
    usage: /<command> [player]
permissions:
  privileges.build:
    default: true
    description: Determines whether or not a player can build.
  privileges.interact:
    default: true
    description: Determines whether or not a player can interact with the game objects.
  privileges.list.other:
    default: false
    description: Allows viewing other peoples permissions node lists.
  privileges.check.other:
    default: false
    description: Allows checking whether a node is set on another user.
  privileges.self.edit:
    default: false
    description: Allows any user with this node to edit any permission they want, regardless of rank.
  privileges.restricted:
    default: false
    description: A set of nodes that restrict a user from interacting and building
    children:
      privileges.build: false
      privileges.interact: false
  privileges.users:
    default: false
    description: A set of nodes for the typical user
    children:
      privileges.build: true
      privileges.check: true
      privileges.help: true
      privileges.info: true
      privileges.interact: true
      privileges.list: true
      privileges.version: true
  privileges.mods:
    default: false
    description: A set of nodes useful for a typical moderator
    children:
      privileges.users: true
      privileges.check.other: true
      privileges.debug: true
      privileges.group.list: true
      privileges.info.other: true
      privileges.list.other: true
      privileges.promote: true
      privileges.demote: true
      privileges.reload: true
  privileges.admins:
    default: false
    description: Sets all user and group permission editing nodes.
    children:
      privileges.mods: true
      privileges.group.*: true
      privileges.user.*: true